[general]
live_config_reload = true
import = ["tokyonight_night.toml"]

[font]
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }

[selection]
save_to_clipboard = true

[window]
padding = { x = 10, y = 10}
